services:
  - type: web
    name: trendmind-option
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      playwright install
    startCommand: gunicorn main:app
